// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/hyperledger/fabric/protos/orderer/kafka.proto

package orderer // import "github.com/hyperledger/fabric/protos/orderer"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KafkaMessageRegular_Class int32

const (
	KafkaMessageRegular_UNKNOWN KafkaMessageRegular_Class = 0
	KafkaMessageRegular_NORMAL  KafkaMessageRegular_Class = 1
	KafkaMessageRegular_CONFIG  KafkaMessageRegular_Class = 2
)

var KafkaMessageRegular_Class_name = map[int32]string{
	0: "UNKNOWN",
	1: "NORMAL",
	2: "CONFIG",
}
var KafkaMessageRegular_Class_value = map[string]int32{
	"UNKNOWN": 0,
	"NORMAL":  1,
	"CONFIG":  2,
}

func (x KafkaMessageRegular_Class) String() string {
	return proto.EnumName(KafkaMessageRegular_Class_name, int32(x))
}
func (KafkaMessageRegular_Class) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_kafka_c8dbefa09952b8ad, []int{1, 0}
}

// KafkaMessage is a wrapper type for the messages
// that the Kafka-based orderer deals with.
type KafkaMessage struct {
	// Types that are valid to be assigned to Type:
	//	*KafkaMessage_Regular
	//	*KafkaMessage_TimeToCut
	//	*KafkaMessage_Connect
	Type                 isKafkaMessage_Type `protobuf_oneof:"Type"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *KafkaMessage) Reset()         { *m = KafkaMessage{} }
func (m *KafkaMessage) String() string { return proto.CompactTextString(m) }
func (*KafkaMessage) ProtoMessage()    {}
func (*KafkaMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_kafka_c8dbefa09952b8ad, []int{0}
}
func (m *KafkaMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KafkaMessage.Unmarshal(m, b)
}
func (m *KafkaMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KafkaMessage.Marshal(b, m, deterministic)
}
func (dst *KafkaMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KafkaMessage.Merge(dst, src)
}
func (m *KafkaMessage) XXX_Size() int {
	return xxx_messageInfo_KafkaMessage.Size(m)
}
func (m *KafkaMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_KafkaMessage.DiscardUnknown(m)
}

var xxx_messageInfo_KafkaMessage proto.InternalMessageInfo

type isKafkaMessage_Type interface {
	isKafkaMessage_Type()
}

type KafkaMessage_Regular struct {
	Regular *KafkaMessageRegular `protobuf:"bytes,1,opt,name=regular,proto3,oneof"`
}

type KafkaMessage_TimeToCut struct {
	TimeToCut *KafkaMessageTimeToCut `protobuf:"bytes,2,opt,name=time_to_cut,json=timeToCut,proto3,oneof"`
}

type KafkaMessage_Connect struct {
	Connect *KafkaMessageConnect `protobuf:"bytes,3,opt,name=connect,proto3,oneof"`
}

func (*KafkaMessage_Regular) isKafkaMessage_Type() {}

func (*KafkaMessage_TimeToCut) isKafkaMessage_Type() {}

func (*KafkaMessage_Connect) isKafkaMessage_Type() {}

func (m *KafkaMessage) GetType() isKafkaMessage_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *KafkaMessage) GetRegular() *KafkaMessageRegular {
	if x, ok := m.GetType().(*KafkaMessage_Regular); ok {
		return x.Regular
	}
	return nil
}

func (m *KafkaMessage) GetTimeToCut() *KafkaMessageTimeToCut {
	if x, ok := m.GetType().(*KafkaMessage_TimeToCut); ok {
		return x.TimeToCut
	}
	return nil
}

func (m *KafkaMessage) GetConnect() *KafkaMessageConnect {
	if x, ok := m.GetType().(*KafkaMessage_Connect); ok {
		return x.Connect
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*KafkaMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _KafkaMessage_OneofMarshaler, _KafkaMessage_OneofUnmarshaler, _KafkaMessage_OneofSizer, []interface{}{
		(*KafkaMessage_Regular)(nil),
		(*KafkaMessage_TimeToCut)(nil),
		(*KafkaMessage_Connect)(nil),
	}
}

func _KafkaMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*KafkaMessage)
	// Type
	switch x := m.Type.(type) {
	case *KafkaMessage_Regular:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Regular); err != nil {
			return err
		}
	case *KafkaMessage_TimeToCut:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TimeToCut); err != nil {
			return err
		}
	case *KafkaMessage_Connect:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Connect); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("KafkaMessage.Type has unexpected type %T", x)
	}
	return nil
}

func _KafkaMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*KafkaMessage)
	switch tag {
	case 1: // Type.regular
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(KafkaMessageRegular)
		err := b.DecodeMessage(msg)
		m.Type = &KafkaMessage_Regular{msg}
		return true, err
	case 2: // Type.time_to_cut
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(KafkaMessageTimeToCut)
		err := b.DecodeMessage(msg)
		m.Type = &KafkaMessage_TimeToCut{msg}
		return true, err
	case 3: // Type.connect
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(KafkaMessageConnect)
		err := b.DecodeMessage(msg)
		m.Type = &KafkaMessage_Connect{msg}
		return true, err
	default:
		return false, nil
	}
}

func _KafkaMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*KafkaMessage)
	// Type
	switch x := m.Type.(type) {
	case *KafkaMessage_Regular:
		s := proto.Size(x.Regular)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *KafkaMessage_TimeToCut:
		s := proto.Size(x.TimeToCut)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *KafkaMessage_Connect:
		s := proto.Size(x.Connect)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// KafkaMessageRegular wraps a marshalled envelope.
type KafkaMessageRegular struct {
	Payload              []byte                    `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	ConfigSeq            uint64                    `protobuf:"varint,2,opt,name=config_seq,json=configSeq,proto3" json:"config_seq,omitempty"`
	Class                KafkaMessageRegular_Class `protobuf:"varint,3,opt,name=class,proto3,enum=orderer.KafkaMessageRegular_Class" json:"class,omitempty"`
	OriginalOffset       int64                     `protobuf:"varint,4,opt,name=original_offset,json=originalOffset,proto3" json:"original_offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *KafkaMessageRegular) Reset()         { *m = KafkaMessageRegular{} }
func (m *KafkaMessageRegular) String() string { return proto.CompactTextString(m) }
func (*KafkaMessageRegular) ProtoMessage()    {}
func (*KafkaMessageRegular) Descriptor() ([]byte, []int) {
	return fileDescriptor_kafka_c8dbefa09952b8ad, []int{1}
}
func (m *KafkaMessageRegular) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KafkaMessageRegular.Unmarshal(m, b)
}
func (m *KafkaMessageRegular) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KafkaMessageRegular.Marshal(b, m, deterministic)
}
func (dst *KafkaMessageRegular) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KafkaMessageRegular.Merge(dst, src)
}
func (m *KafkaMessageRegular) XXX_Size() int {
	return xxx_messageInfo_KafkaMessageRegular.Size(m)
}
func (m *KafkaMessageRegular) XXX_DiscardUnknown() {
	xxx_messageInfo_KafkaMessageRegular.DiscardUnknown(m)
}

var xxx_messageInfo_KafkaMessageRegular proto.InternalMessageInfo

func (m *KafkaMessageRegular) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *KafkaMessageRegular) GetConfigSeq() uint64 {
	if m != nil {
		return m.ConfigSeq
	}
	return 0
}

func (m *KafkaMessageRegular) GetClass() KafkaMessageRegular_Class {
	if m != nil {
		return m.Class
	}
	return KafkaMessageRegular_UNKNOWN
}

func (m *KafkaMessageRegular) GetOriginalOffset() int64 {
	if m != nil {
		return m.OriginalOffset
	}
	return 0
}

// KafkaMessageTimeToCut is used to signal to the orderers
// that it is time to cut block <block_number>.
type KafkaMessageTimeToCut struct {
	BlockNumber          uint64   `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KafkaMessageTimeToCut) Reset()         { *m = KafkaMessageTimeToCut{} }
func (m *KafkaMessageTimeToCut) String() string { return proto.CompactTextString(m) }
func (*KafkaMessageTimeToCut) ProtoMessage()    {}
func (*KafkaMessageTimeToCut) Descriptor() ([]byte, []int) {
	return fileDescriptor_kafka_c8dbefa09952b8ad, []int{2}
}
func (m *KafkaMessageTimeToCut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KafkaMessageTimeToCut.Unmarshal(m, b)
}
func (m *KafkaMessageTimeToCut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KafkaMessageTimeToCut.Marshal(b, m, deterministic)
}
func (dst *KafkaMessageTimeToCut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KafkaMessageTimeToCut.Merge(dst, src)
}
func (m *KafkaMessageTimeToCut) XXX_Size() int {
	return xxx_messageInfo_KafkaMessageTimeToCut.Size(m)
}
func (m *KafkaMessageTimeToCut) XXX_DiscardUnknown() {
	xxx_messageInfo_KafkaMessageTimeToCut.DiscardUnknown(m)
}

var xxx_messageInfo_KafkaMessageTimeToCut proto.InternalMessageInfo

func (m *KafkaMessageTimeToCut) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

// KafkaMessageConnect is posted by an orderer upon booting up.
// It is used to prevent the panic that would be caused if we
// were to consume an empty partition. It is ignored by all
// orderers when processing the partition.
type KafkaMessageConnect struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KafkaMessageConnect) Reset()         { *m = KafkaMessageConnect{} }
func (m *KafkaMessageConnect) String() string { return proto.CompactTextString(m) }
func (*KafkaMessageConnect) ProtoMessage()    {}
func (*KafkaMessageConnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_kafka_c8dbefa09952b8ad, []int{3}
}
func (m *KafkaMessageConnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KafkaMessageConnect.Unmarshal(m, b)
}
func (m *KafkaMessageConnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KafkaMessageConnect.Marshal(b, m, deterministic)
}
func (dst *KafkaMessageConnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KafkaMessageConnect.Merge(dst, src)
}
func (m *KafkaMessageConnect) XXX_Size() int {
	return xxx_messageInfo_KafkaMessageConnect.Size(m)
}
func (m *KafkaMessageConnect) XXX_DiscardUnknown() {
	xxx_messageInfo_KafkaMessageConnect.DiscardUnknown(m)
}

var xxx_messageInfo_KafkaMessageConnect proto.InternalMessageInfo

func (m *KafkaMessageConnect) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// KafkaMetadata is encoded into the ORDERER block to keep track of
// Kafka-related metadata associated with this block.
type KafkaMetadata struct {
	// LastOffsetPersisted is the encoded value for the Metadata message
	// which is encoded in the ORDERER block metadata index for the case
	// of the Kafka-based orderer.
	LastOffsetPersisted int64 `protobuf:"varint,1,opt,name=last_offset_persisted,json=lastOffsetPersisted,proto3" json:"last_offset_persisted,omitempty"`
	// LastOriginalOffsetProcessed is used to keep track of the newest
	// offset processed if a message is re-validated and re-ordered.
	// This value is used to deduplicate re-submitted messages from
	// multiple orderer so that we don't bother re-processing it again.
	LastOriginalOffsetProcessed int64 `protobuf:"varint,2,opt,name=last_original_offset_processed,json=lastOriginalOffsetProcessed,proto3" json:"last_original_offset_processed,omitempty"`
	// LastResubmittedConfigOffset is used to capture the newest offset of
	// CONFIG kafka message, which is revalidated and resubmitted. By comparing
	// this with LastOriginalOffsetProcessed, we could detemine whether there
	// are still CONFIG messages that have been resubmitted but NOT processed
	// yet. It's used as condition to block ingress messages, so we could reduce
	// the overhead of repeatedly resubmitting messages as config seq keeps
	// advancing.
	LastResubmittedConfigOffset int64           `protobuf:"varint,3,opt,name=last_resubmitted_config_offset,json=lastResubmittedConfigOffset,proto3" json:"last_resubmitted_config_offset,omitempty"`
	ReceivedTTCMessage          bool            `protobuf:"varint,4,opt,name=received_t_t_c_message,json=receivedTTCMessage,proto3" json:"received_t_t_c_message,omitempty"`
	TTCPayload                  *KafkaPayload   `protobuf:"bytes,5,opt,name=t_t_c_payload,json=tTCPayload,proto3" json:"t_t_c_payload,omitempty"`
	ReceivedConnectOrTTCMessage bool            `protobuf:"varint,6,opt,name=received_connect_or_t_t_c_message,json=receivedConnectOrTTCMessage,proto3" json:"received_connect_or_t_t_c_message,omitempty"`
	ConnectOrTTCPayload         []*KafkaPayload `protobuf:"bytes,7,rep,name=connect_or_t_t_c_payload,json=connectOrTTCPayload,proto3" json:"connect_or_t_t_c_payload,omitempty"`
	IsConfigMessage             bool            `protobuf:"varint,8,opt,name=is_config_message,json=isConfigMessage,proto3" json:"is_config_message,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}        `json:"-"`
	XXX_unrecognized            []byte          `json:"-"`
	XXX_sizecache               int32           `json:"-"`
}

func (m *KafkaMetadata) Reset()         { *m = KafkaMetadata{} }
func (m *KafkaMetadata) String() string { return proto.CompactTextString(m) }
func (*KafkaMetadata) ProtoMessage()    {}
func (*KafkaMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_kafka_c8dbefa09952b8ad, []int{4}
}
func (m *KafkaMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KafkaMetadata.Unmarshal(m, b)
}
func (m *KafkaMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KafkaMetadata.Marshal(b, m, deterministic)
}
func (dst *KafkaMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KafkaMetadata.Merge(dst, src)
}
func (m *KafkaMetadata) XXX_Size() int {
	return xxx_messageInfo_KafkaMetadata.Size(m)
}
func (m *KafkaMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_KafkaMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_KafkaMetadata proto.InternalMessageInfo

func (m *KafkaMetadata) GetLastOffsetPersisted() int64 {
	if m != nil {
		return m.LastOffsetPersisted
	}
	return 0
}

func (m *KafkaMetadata) GetLastOriginalOffsetProcessed() int64 {
	if m != nil {
		return m.LastOriginalOffsetProcessed
	}
	return 0
}

func (m *KafkaMetadata) GetLastResubmittedConfigOffset() int64 {
	if m != nil {
		return m.LastResubmittedConfigOffset
	}
	return 0
}

func (m *KafkaMetadata) GetReceivedTTCMessage() bool {
	if m != nil {
		return m.ReceivedTTCMessage
	}
	return false
}

func (m *KafkaMetadata) GetTTCPayload() *KafkaPayload {
	if m != nil {
		return m.TTCPayload
	}
	return nil
}

func (m *KafkaMetadata) GetReceivedConnectOrTTCMessage() bool {
	if m != nil {
		return m.ReceivedConnectOrTTCMessage
	}
	return false
}

func (m *KafkaMetadata) GetConnectOrTTCPayload() []*KafkaPayload {
	if m != nil {
		return m.ConnectOrTTCPayload
	}
	return nil
}

func (m *KafkaMetadata) GetIsConfigMessage() bool {
	if m != nil {
		return m.IsConfigMessage
	}
	return false
}

type KafkaPayload struct {
	KafkaMerkleProofHeader []byte   `protobuf:"bytes,1,opt,name=kafka_merkle_proof_header,json=kafkaMerkleProofHeader,proto3" json:"kafka_merkle_proof_header,omitempty"`
	KafkaSignatureHeader   []byte   `protobuf:"bytes,2,opt,name=kafka_signature_header,json=kafkaSignatureHeader,proto3" json:"kafka_signature_header,omitempty"`
	ConsumerMessageBytes   []byte   `protobuf:"bytes,3,opt,name=consumer_message_bytes,json=consumerMessageBytes,proto3" json:"consumer_message_bytes,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *KafkaPayload) Reset()         { *m = KafkaPayload{} }
func (m *KafkaPayload) String() string { return proto.CompactTextString(m) }
func (*KafkaPayload) ProtoMessage()    {}
func (*KafkaPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_kafka_c8dbefa09952b8ad, []int{5}
}
func (m *KafkaPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KafkaPayload.Unmarshal(m, b)
}
func (m *KafkaPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KafkaPayload.Marshal(b, m, deterministic)
}
func (dst *KafkaPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KafkaPayload.Merge(dst, src)
}
func (m *KafkaPayload) XXX_Size() int {
	return xxx_messageInfo_KafkaPayload.Size(m)
}
func (m *KafkaPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_KafkaPayload.DiscardUnknown(m)
}

var xxx_messageInfo_KafkaPayload proto.InternalMessageInfo

func (m *KafkaPayload) GetKafkaMerkleProofHeader() []byte {
	if m != nil {
		return m.KafkaMerkleProofHeader
	}
	return nil
}

func (m *KafkaPayload) GetKafkaSignatureHeader() []byte {
	if m != nil {
		return m.KafkaSignatureHeader
	}
	return nil
}

func (m *KafkaPayload) GetConsumerMessageBytes() []byte {
	if m != nil {
		return m.ConsumerMessageBytes
	}
	return nil
}

func init() {
	proto.RegisterType((*KafkaMessage)(nil), "orderer.KafkaMessage")
	proto.RegisterType((*KafkaMessageRegular)(nil), "orderer.KafkaMessageRegular")
	proto.RegisterType((*KafkaMessageTimeToCut)(nil), "orderer.KafkaMessageTimeToCut")
	proto.RegisterType((*KafkaMessageConnect)(nil), "orderer.KafkaMessageConnect")
	proto.RegisterType((*KafkaMetadata)(nil), "orderer.KafkaMetadata")
	proto.RegisterType((*KafkaPayload)(nil), "orderer.KafkaPayload")
	proto.RegisterEnum("orderer.KafkaMessageRegular_Class", KafkaMessageRegular_Class_name, KafkaMessageRegular_Class_value)
}

func init() {
	proto.RegisterFile("github.com/hyperledger/fabric/protos/orderer/kafka.proto", fileDescriptor_kafka_c8dbefa09952b8ad)
}

var fileDescriptor_kafka_c8dbefa09952b8ad = []byte{
	// 656 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdb, 0x4e, 0x1b, 0x3b,
	0x14, 0x25, 0x24, 0x24, 0xe0, 0x84, 0xcb, 0x31, 0x17, 0xe5, 0x88, 0x73, 0x10, 0xcc, 0x4b, 0x51,
	0x85, 0x12, 0x29, 0xed, 0x03, 0xed, 0x53, 0xcb, 0x48, 0x94, 0x0a, 0x48, 0x22, 0x93, 0xaa, 0x52,
	0x5f, 0x2c, 0xcf, 0xcc, 0xce, 0x30, 0xca, 0xcc, 0x38, 0xd8, 0x9e, 0x4a, 0xf9, 0xb0, 0xfe, 0x45,
	0xff, 0xa1, 0x5f, 0x52, 0xa9, 0x1a, 0x5f, 0x08, 0x69, 0x01, 0xa9, 0x6f, 0xe3, 0xbd, 0xd6, 0xf2,
	0x5e, 0x5e, 0xde, 0x63, 0x74, 0x1a, 0x27, 0xea, 0xb6, 0x08, 0x3a, 0x21, 0xcf, 0xba, 0xb7, 0xb3,
	0x29, 0x88, 0x14, 0xa2, 0x18, 0x44, 0x77, 0xcc, 0x02, 0x91, 0x84, 0xdd, 0xa9, 0xe0, 0x8a, 0xcb,
	0x2e, 0x17, 0x11, 0x08, 0x10, 0xdd, 0x09, 0x1b, 0x4f, 0x58, 0x47, 0x17, 0x71, 0xc3, 0x16, 0xbd,
	0xef, 0x15, 0xd4, 0xba, 0x2c, 0x81, 0x6b, 0x90, 0x92, 0xc5, 0x80, 0x4f, 0x51, 0x43, 0x40, 0x5c,
	0xa4, 0x4c, 0xb4, 0x2b, 0x87, 0x95, 0xe3, 0x66, 0xef, 0xbf, 0x8e, 0xe5, 0x76, 0x1e, 0xf2, 0x88,
	0xe1, 0x5c, 0x2c, 0x11, 0x47, 0xc7, 0xef, 0x50, 0x53, 0x25, 0x19, 0x50, 0xc5, 0x69, 0x58, 0xa8,
	0xf6, 0xb2, 0x56, 0x1f, 0x3c, 0xaa, 0x1e, 0x25, 0x19, 0x8c, 0xb8, 0x5f, 0xa8, 0x8b, 0x25, 0xb2,
	0xa6, 0xdc, 0xa2, 0xec, 0x1d, 0xf2, 0x3c, 0x87, 0x50, 0xb5, 0xab, 0xcf, 0xf4, 0xf6, 0x0d, 0xa7,
	0xec, 0x6d, 0xe9, 0x67, 0x75, 0x54, 0x1b, 0xcd, 0xa6, 0xe0, 0xfd, 0xa8, 0xa0, 0xed, 0x47, 0x6c,
	0xe2, 0x36, 0x6a, 0x4c, 0xd9, 0x2c, 0xe5, 0x2c, 0xd2, 0xa7, 0x6a, 0x11, 0xb7, 0xc4, 0xff, 0x23,
	0x14, 0xf2, 0x7c, 0x9c, 0xc4, 0x54, 0xc2, 0x9d, 0x36, 0x5d, 0x23, 0x6b, 0xa6, 0x72, 0x03, 0x77,
	0xf8, 0x14, 0xad, 0x84, 0x29, 0x93, 0x52, 0x1b, 0xda, 0xe8, 0x79, 0xcf, 0x85, 0xd1, 0xf1, 0x4b,
	0x26, 0x31, 0x02, 0xfc, 0x02, 0x6d, 0x72, 0x91, 0xc4, 0x49, 0xce, 0x52, 0xca, 0xc7, 0x63, 0x09,
	0xaa, 0x5d, 0x3b, 0xac, 0x1c, 0x57, 0xc9, 0x86, 0x2b, 0x0f, 0x74, 0xd5, 0x3b, 0x41, 0x2b, 0x5a,
	0x88, 0x9b, 0xa8, 0xf1, 0xa9, 0x7f, 0xd9, 0x1f, 0x7c, 0xee, 0x6f, 0x2d, 0x61, 0x84, 0xea, 0xfd,
	0x01, 0xb9, 0x7e, 0x7f, 0xb5, 0x55, 0x29, 0xbf, 0xfd, 0x41, 0xff, 0xfc, 0xe3, 0x87, 0xad, 0x65,
	0xef, 0x2d, 0xda, 0x7d, 0x34, 0x49, 0x7c, 0x84, 0x5a, 0x41, 0xca, 0xc3, 0x09, 0xcd, 0x8b, 0x2c,
	0x00, 0x73, 0x7b, 0x35, 0xd2, 0xd4, 0xb5, 0xbe, 0x2e, 0x79, 0xdd, 0xc5, 0x70, 0x6c, 0x8e, 0x4f,
	0x87, 0xe3, 0xfd, 0xac, 0xa2, 0x75, 0xab, 0x50, 0x2c, 0x62, 0x8a, 0xe1, 0x1e, 0xda, 0x4d, 0x99,
	0x54, 0xf6, 0x44, 0x74, 0x0a, 0x42, 0x26, 0x52, 0x81, 0x51, 0x56, 0xc9, 0x76, 0x09, 0x9a, 0x73,
	0x0d, 0x1d, 0x84, 0x7d, 0x74, 0x60, 0x34, 0x8b, 0x71, 0xd0, 0xa9, 0xe0, 0x21, 0x48, 0x09, 0x91,
	0x8e, 0xbd, 0x4a, 0xf6, 0xb5, 0x78, 0x21, 0x9c, 0xa1, 0xa3, 0xdc, 0x6f, 0x22, 0x40, 0x16, 0x41,
	0x96, 0x28, 0x05, 0x11, 0xb5, 0x17, 0x67, 0xd3, 0xad, 0xce, 0x37, 0x21, 0x73, 0x92, 0xaf, 0x39,
	0x66, 0x37, 0xdc, 0x43, 0x7b, 0x02, 0x42, 0x48, 0xbe, 0x42, 0x44, 0x15, 0x55, 0x34, 0xa4, 0x99,
	0x89, 0x42, 0x5f, 0xcd, 0x2a, 0xc1, 0x0e, 0x1d, 0x8d, 0xfc, 0xf9, 0x0f, 0xb1, 0x6e, 0xa8, 0x2e,
	0xa3, 0x15, 0x3d, 0x9a, 0xbb, 0x8b, 0x93, 0x30, 0x34, 0x20, 0x41, 0x6a, 0xe4, 0xdb, 0x6f, 0x7c,
	0x8e, 0x8e, 0xee, 0xbb, 0xd9, 0x41, 0xa5, 0x5c, 0xfc, 0xd6, 0xb8, 0xae, 0x1b, 0xef, 0x3b, 0xa2,
	0xbd, 0x93, 0x81, 0x78, 0xe0, 0xe0, 0x0a, 0xb5, 0xff, 0x90, 0x3b, 0x33, 0x8d, 0xc3, 0xea, 0xd3,
	0x66, 0xb6, 0xc3, 0x07, 0xbb, 0x39, 0x57, 0x2f, 0xd1, 0x3f, 0x89, 0x74, 0xd1, 0x39, 0x17, 0xab,
	0xda, 0xc5, 0x66, 0x22, 0x4d, 0x5c, 0xb6, 0xb3, 0xf7, 0xcd, 0xbd, 0x0e, 0x4e, 0xfc, 0x06, 0xfd,
	0xab, 0x9f, 0x11, 0x9a, 0x81, 0x98, 0xa4, 0x50, 0x5e, 0x21, 0x1f, 0xd3, 0x5b, 0x60, 0x91, 0x9d,
	0xb8, 0x16, 0xd9, 0x9b, 0x98, 0x81, 0x29, 0xf1, 0x61, 0x09, 0x5f, 0x68, 0x14, 0xbf, 0x46, 0x06,
	0xa1, 0x32, 0x89, 0x73, 0xa6, 0x0a, 0x01, 0x4e, 0xb7, 0xac, 0x75, 0x3b, 0x1a, 0xbd, 0x71, 0xe0,
	0x5c, 0x15, 0xf2, 0x5c, 0x16, 0x19, 0x08, 0x67, 0x96, 0x06, 0x33, 0x05, 0xe6, 0x87, 0x6c, 0x91,
	0x1d, 0x87, 0x5a, 0xcb, 0x67, 0x25, 0x76, 0xd6, 0xf9, 0x72, 0xf2, 0x37, 0x4f, 0x63, 0x50, 0xd7,
	0xeb, 0x57, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6b, 0xf0, 0xe7, 0xa3, 0x51, 0x05, 0x00, 0x00,
}
